### Configure a variable for the web service base address.
@base_address = http://localhost:8080/artists

###
POST {{base_address}}
Authorization: Basic user:user123
Content-Type: application/json

{
"name":"Threadbare Loaf"
}

###
POST {{base_address}}
Authorization: Basic user:user123
Content-Type: application/json

{
"name":"Therapy Zeppelin"
}

###
GET {{base_address}}
Authorization: Basic user:user123

###
GET {{base_address}}/1
Authorization: Basic user:user123
###
GET {{base_address}}/search/Threadbare%20Loaf
Authorization: Basic user:user123
###
GET {{base_address}}/match/Threadbare
Authorization: Basic user:user123
###
GET {{base_address}}/match/
Authorization: Basic user:user123